---
- name: Install browsers (Debian-based)
  become: true
  block:
    - name: Download Chrome package
      ansible.builtin.get_url:
        url: "https://dl.google.com/linux/direct/google-chrome-stable_current_{{ apt_arch }}.deb"
        dest: /tmp/google-chrome.deb

    - name: Install Chrome
      ansible.builtin.apt:
        deb: /tmp/google-chrome.deb

    - name: Install Firefox
      ansible.builtin.apt:
        name: firefox
        state: present

    - name: Install Chromium
      ansible.builtin.apt:
        name: chromium
        state: present

    - name: Remove Chrome .deb
      ansible.builtin.file:
        path: /tmp/google-chrome.deb
        state: absent
  when: ansible_os_family == "Debian"

- name: Install browsers (Fedora-based)
  become: true
  block:
    - name: Import Google GPG key
      ansible.builtin.rpm_key:
        key: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Download Chrome package
      ansible.builtin.get_url:
        url: "https://dl.google.com/linux/direct/google-chrome-stable_current_{{ ansible_architecture }}.rpm"
        dest: /tmp/google-chrome.rpm

    - name: Install Chrome
      ansible.builtin.dnf:
        name: /tmp/google-chrome.rpm
        state: present

    - name: Install Firefox
      ansible.builtin.dnf:
        name: firefox
        state: present

    - name: Install Chromium
      ansible.builtin.dnf:
        name: chromium
        state: present

    - name: Remove Chrome .rpm
      ansible.builtin.file:
        path: /tmp/google-chrome.rpm
        state: absent
  when: ansible_os_family == "RedHat"
