---
- name: Install required dependencies (apt)
  become: true
  ansible.builtin.apt:
    name: "{{ packages_debian }}"
    state: present
    update_cache: true

- name: Install common packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages_common }}"
    state: present

- name: Ensure snapd is running
  become: true
  ansible.builtin.systemd:
    name: snapd
    state: started
    enabled: true

- name: Upgrade all packages (apt)
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  tags:
    - upgrade
    - never
