---
- name: Get installed VS Code extensions
  ansible.builtin.command: code --list-extensions
  register: installed_extensions
  changed_when: false
  failed_when: false

- name: Install VS Code extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  when: item not in installed_extensions.stdout_lines
  changed_when: true
  ignore_errors: true
