---
- block:
  - name: Check if 1Password GPG key imported
    shell:
      cmd: ls /usr/share/keyrings/1password-archive-keyring.gpg
    register: gpg_bool
    ignore_errors: true

  - name: Import 1Password GPG key
    become: true
    shell: "curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor -o /usr/share/keyrings/1password-archive-keyring.gpg"
    when: gpg_bool.failed

  - name: Add 1Password repository
    become: true
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
      filename: 1password

  - name: Install 1Password and CLI
    become: true
    apt:
      name:
        - 1password
        - 1password-cli
      state: present
      update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - always

- block:
  - name: Import 1Password GPG key
    become: true
    rpm_key:
      key: https://downloads.1password.com/linux/keys/1password.asc
      state: present

  - name: Add 1Password repository
    become: true
    yum_repository:
      name: 1password
      description: 1Password
      baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
      gpgcheck: yes
      enabled: yes
      gpgkey: https://downloads.1password.com/linux/keys/1password.asc

  - name: Install 1Password and CLI
    become: true
    dnf:
      name:
        - 1password
        - 1password-cli
      state: present
  when: ansible_os_family == "RedHat"
  tags:
    - always
