---
- name: Install 1Password (Debian-based)
  block:
    - name: Check if 1Password GPG key exists
      ansible.builtin.stat:
        path: /usr/share/keyrings/1password-archive-keyring.gpg
      register: onepassword_gpg_key

    - name: Import 1Password GPG key
      become: true
      ansible.builtin.shell:
        cmd: "curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor -o /usr/share/keyrings/1password-archive-keyring.gpg"
      when: not onepassword_gpg_key.stat.exists
      changed_when: not onepassword_gpg_key.stat.exists

    - name: Add 1Password repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ apt_arch }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ apt_arch }} stable main"
        filename: 1password

    - name: Install 1Password and CLI
      become: true
      ansible.builtin.apt:
        name:
          - 1password
          - 1password-cli
        state: present
        update_cache: true
  when: ansible_os_family == "Debian"

- name: Install 1Password (Fedora-based)
  block:
    - name: Import 1Password GPG key
      become: true
      ansible.builtin.rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present

    - name: Add 1Password repository
      become: true
      ansible.builtin.yum_repository:
        name: 1password
        description: 1Password
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        gpgcheck: true
        enabled: true
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc

    - name: Install 1Password and CLI
      become: true
      ansible.builtin.dnf:
        name:
          - 1password
          - 1password-cli
        state: present
  when: ansible_os_family == "RedHat"
