---
- name: Get latest version
  uri:
    url: https://api.github.com/repos/Yubico/yubioath-flutter/releases/latest
    return_content: true
  register: json_response
  tags:
    - always

- name: Set version fact
  set_fact:
    latest_version: "{{ json_response.json.tag_name }}"
  tags:
    - always

- name: Make yubico dir
  become: true
  file:
    path: /opt/yubico
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - always

- name: Download latest Yubico App
  become: true
  get_url:
    url: https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz
    dest: /opt/yubico-authenticator-latest-linux.tar.gz
  tags:
    - always

- name: Extract Yubico tarball
  become: true
  unarchive:
    src: /opt/yubico-authenticator-latest-linux.tar.gz
    dest: /opt/yubico
    remote_src: true
  tags:
    - always

- name: Run desktop integration script
  shell: "/opt/yubico/yubico-authenticator-{{ latest_version }}-linux/desktop_integration.sh --install"
  tags:
    - always

- name: Clean up .tar.gz
  become: true
  file:
    path: /opt/yubico-authenticator-latest-linux.tar.gz
    state: absent
  tags:
    - always
