---
- name: Set host user fact
  ansible.builtin.set_fact:
    host_user: "{{ ansible_user_id }}"
  tags:
    - always

- name: Set apt architecture fact
  ansible.builtin.set_fact:
    apt_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ('arm64' if ansible_architecture == 'aarch64' else ansible_architecture) }}"
  when: ansible_os_family == "Debian"
  tags:
    - always
